name: On PR

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  BASE_DOCKERFILE: 11.1-cudnn8-u20.04/Dockerfile

jobs:
  arch-86:
    runs-on: ubuntu-20.04
    env:
      CUDA_ARCH: 86
    steps:
    - uses: actions/checkout@v2
    - name: Build Test
      run: |
        docker build --build-arg CUDA_ARCH=$CUDA_ARCH --pull -t dev/build:test-$CUDA_ARCH -f $BASE_DOCKERFILE .
  arch-80:
    runs-on: ubuntu-20.04
    env:
      CUDA_ARCH: 80
    steps:
    - uses: actions/checkout@v2
    - name: Build Test
      run: |
        docker build --build-arg CUDA_ARCH=$CUDA_ARCH --pull -t dev/build:test-$CUDA_ARCH -f $BASE_DOCKERFILE .
  arch-75:
    runs-on: ubuntu-20.04
    env:
      CUDA_ARCH: 75
    steps:
    - uses: actions/checkout@v2
    - name: Build Test
      run: |
        docker build --build-arg CUDA_ARCH=$CUDA_ARCH --pull -t dev/build:test-$CUDA_ARCH -f $BASE_DOCKERFILE .
  arch-70:
    runs-on: ubuntu-20.04
    env:
      CUDA_ARCH: 70
    steps:
    - uses: actions/checkout@v2
    - name: Build Test
      run: |
        docker build --build-arg CUDA_ARCH=$CUDA_ARCH --pull -t dev/build:test-$CUDA_ARCH -f $BASE_DOCKERFILE .
  arch-61:
    runs-on: ubuntu-20.04
    env:
      CUDA_ARCH: 61
    steps:
    - uses: actions/checkout@v2
    - name: Build Test
      run: |
        docker build --build-arg CUDA_ARCH=$CUDA_ARCH --pull -t dev/build:test-$CUDA_ARCH -f $BASE_DOCKERFILE .
  arch-60:
    runs-on: ubuntu-20.04
    env:
      CUDA_ARCH: 60
    steps:
    - uses: actions/checkout@v2
    - name: Build Test
      run: |
        docker build --build-arg CUDA_ARCH=$CUDA_ARCH --pull -t dev/build:test-$CUDA_ARCH -f $BASE_DOCKERFILE .
  arch-52:
    runs-on: ubuntu-20.04
    env:
      CUDA_ARCH: 52
    steps:
    - uses: actions/checkout@v2
    - name: Build Test
      run: |
        docker build --build-arg CUDA_ARCH=$CUDA_ARCH --pull -t dev/build:test-$CUDA_ARCH -f $BASE_DOCKERFILE .
